CRUD

C - CREATE - 
R - READ - LISTAGEM DE DADOS
U - UPDATE - FALTA FAZER
D - DELETE - FEITO


---------
REST FUL API
VERBOS http

URL + GET =  CONSULTAR DADOS
URL/ID + GET =  CONSULTAR UM REGISTRO
URL + DADOS + POST = CRIAR DADOS
URL/ID + PUT = ALTERAR DADOS
URL/ID + DELETE = DELETAR DADOS